CREATE TABLE THONG_SO_KY_THUAT (
    MA_THONG_SO INT PRIMARY KEY,
    TEN_THONG_SO VARCHAR(255) NOT NULL
);

CREATE TABLE THONG_SO_AP_SUAT (
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    MA_TSAP INT PRIMARY KEY,
    TEN_TSAP VARCHAR(255) NOT NULL
);

CREATE TABLE MAT_DONG_HO (
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    MA_MAT INT PRIMARY KEY,
);

CREATE TABLE NGUON_NANG_LUONG (
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    MA_NNL INT PRIMARY KEY,
    TEN_NNL VARCHAR(255) NOT NULL
);
CREATE TABLE THOI_GIAN_SU_DUNG (
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    MA_TGSD INT PRIMARY KEY,
    TEN_TGSD VARCHAR(255) NOT NULL
);
CREATE TABLE HINH_DANG (
    MA_HINH_DANG INT PRIMARY KEY,
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    #MA_MAT INT FOREIGN KEY REFERENCES MAT_DONG_HO(MA_MAT),
    TEN_HINH_DANG VARCHAR(255) NOT NULL
);
CREATE TABLE KICH_THUOC_MAT (
    MA_KICH_THUOC INT PRIMARY KEY,
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    #MA_MAT INT FOREIGN KEY REFERENCES MAT_DONG_HO(MA_MAT),
    KICH_THUOC VARCHAR(255) NOT NULL
);
CREATE TABLE CHAT_LIEU_MAT_KINH (
    MA_CLMK INT PRIMARY KEY,
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    #MA_MAT INT FOREIGN KEY REFERENCES MAT_DONG_HO(MA_MAT),
    TEN_CLMK VARCHAR(255) NOT NULL
);
CREATE TABLE CHAT_LIEU_DAY (
    MA_CLD INT PRIMARY KEY,
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    TEN_CLD VARCHAR(255) NOT NULL
);
CREATE TABLE MAU_SAC (
    MA_MAU INT PRIMARY KEY,
    #MA_THONG_SO INT FOREIGN KEY REFERENCES THONG_SO_KY_THUAT(MA_THONG_SO),
    TEN_MAU VARCHAR(255) NOT NULL
);
CREATE TABLE DONG_SAN_PHAM (
    MA_DONG_SAN_PHAM INT PRIMARY KEY,
    TEN_DONG_SAN_PHAM VARCHAR(255) NOT NULL,
    #MA_THONG_SO INT FOREIGN KEY REFERENCES TH
CREATE TABLE SANPHAM_TINHNANG (
    #MA_TINH INT FOREIGN KEY REFERENCES TINH_NANG(MA_TINH_NANG),
    #MA_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    PRIMARY KEY (#MA_TINH, #MA_SAN_PHAM)
);
CREATE TABLE TINH_NANG (
    MA_TINH_NANG INT PRIMARY KEY,
    TEN_TINH_NANG VARCHAR(255) NOT NULL
);
CREATE TABLE SANPHAM_DOITUONGSUDUNG (
    #MA_DOI_TUONG INT FOREIGN KEY REFERENCES DOI_TUONG_SU_DUNG(MA_DOI_TUONG),
    #MA_DONG_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    PRIMARY KEY (#MA_DOI_TUONG, #MA_DONG_SAN_PHAM)
);
CREATE TABLE DOI_TUONG_SU_DUNG (
    MA_DOI_TUONG INT PRIMARY KEY,
    TEN_DOI_TUONG VARCHAR(255) NOT NULL
);
CREATE TABLE CHUONG_TRINH_KHUYEN_MAI (
    #MA_DONG_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    MA_GIAM_GIA INT PRIMARY KEY,
    TEN_KHUYEN_MAI VARCHAR(255) NOT NULL,
    NGAY_BAT_DAU DATE NOT NULL,
    NGAY_KET_THUC DATE NOT NULL
);
CREATE TABLE GIA (
    #MA_THUONG_HIEU INT FOREIGN KEY REFERENCES THUONG_HIEU(MA_THUONG_HIEU),
    #MA_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    GIA DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (#MA_THUONG_HIEU, #MA_SAN_PHAM)
);
CREATE TABLE THUONG_HIEU (
    MA_THUONG_HIEU INT PRIMARY KEY,
    TEN_THUONG_HIEU VARCHAR(255) NOT NULL,
    #MA_QUOC_GIA INT FOREIGN KEY REFERENCES QUOC_GIA(MA_QUOC_GIA)
);
CREATE TABLE QUOC_GIA (
    MA_QUOC_GIA INT PRIMARY KEY,
    TEN_QUOC_GIA VARCHAR(255) NOT NULL
);
CREATE TABLE LOAI (
    MA_LOAI INT PRIMARY KEY,
    TEN_LOAI VARCHAR(255) NOT NULL,
    #MA_THUONG_HIEU INT FOREIGN KEY REFERENCES THUONG_HIEU(MA_THUONG_HIEU)
);
CREATE TABLE KHO_HANG (
    #MA_PHIEU_NHAP INT FOREIGN KEY REFERENCES PHIEU_NHAP(MA_PHIEU_NHAP),
    #MA_DONG_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    SO_LUONG_TON_KHO INT NOT NULL,
    THOI_GIAN_LUU_TRU INT NOT NULL,
    PRIMARY KEY (#MA_PHIEU_NHAP, #MA_DONG_SAN_PHAM)
);
CREATE TABLE PHIEU_NHAP (
    MA_PHIEU_NHAP INT PRIMARY KEY,
    #TEN_
CREATE TABLE PHIEU_NHAP (
    MA_PHIEU_NHAP INT PRIMARY KEY,
    #TEN_DANG_NHAP VARCHAR(255) FOREIGN KEY REFERENCES TAI_KHOAN(TEN_DANG_NHAP),
    NGAY_NHAP DATE NOT NULL
);
CREATE TABLE CHIEC_DONG_HO (
    SO_SERIAL VARCHAR(255) PRIMARY KEY,
    #MA_DONG_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    #MA_PHIEU_BAO_HANH INT FOREIGN KEY REFERENCES PHIEU_BAO_HANH(MA_PHIEU_BAO_HANH),
    #MA_HOA_DON INT FOREIGN KEY REFERENCES HOA_DON(MA_HOA_DON)
);
CREATE TABLE HOA_DON (
    MA_HOA_DON INT PRIMARY KEY,
    #TEN_DANG_NHAP VARCHAR(255) FOREIGN KEY REFERENCES TAI_KHOAN(TEN_DANG_NHAP),
    THOI_GIAN_XUAT_HOA_DON DATETIME NOT NULL
);
CREATE TABLE PHIEU_BAO_HANH (
    MA_PHIEU_BAO_HANH INT PRIMARY KEY,
    NGAY_BAT_DAU DATE NOT NULL,
    NGAY_KET_THUC DATE NOT NULL
);
CREATE TABLE CHI_TIET_HOA_DON (
    MA_HOA_DON INT FOREIGN KEY REFERENCES HOA_DON(MA_HOA_DON),
    DON_GIA DECIMAL(18,2) NOT NULL,
    SO_LUONG INT NOT NULL,
    PRIMARY KEY (MA_HOA_DON)
);
CREATE TABLE TAI_KHOAN (
    TEN_DANG_NHAP VARCHAR(255) PRIMARY KEY,
    MAT_KHAU VARCHAR(255) NOT NULL
);
CREATE TABLE KHACH_HANG (
    MA_KHACH_HANG INT PRIMARY KEY,
    #TEN_DANG_NHAP VARCHAR(255) FOREIGN KEY REFERENCES TAI_KHOAN(TEN_DANG_NHAP)
);
CREATE TABLE NHAN_VIEN (
    MA_NHAN_VIEN INT PRIMARY KEY,
    #TEN_DANG_NHAP VARCHAR(255) FOREIGN KEY REFERENCES TAI_KHOAN(TEN_DANG_NHAP),
    MA_BO_PHAN INT FOREIGN KEY REFERENCES BO_PHAN(MA_BO_PHAN)
);
CREATE TABLE BO_PHAN (
    MA_BO_PHAN INT PRIMARY KEY,
    TEN_BO_PHAN VARCHAR(255) NOT NULL
);
CREATE TABLE CHUC_VU (
    MA_CHUC_VU INT PRIMARY KEY,
    #TEN_DANG_NHAP VARCHAR(255) FOREIGN KEY REFERENCES TAI_KHOAN(TEN_DANG_NHAP),
    LOAI_CHUC_VU VARCHAR(255) NOT NULL
);
CREATE TABLE THONG_TIN_CA_NHAN (
    MA_TT INT PRIMARY KEY,
    #TEN_DANG_NHAP VARCHAR(255) FOREIGN KEY REFERENCES TAI_KHOAN(TEN_DANG_NHAP),
    HO_TEN VARCHAR(255) NOT NULL,
    SDT VARCHAR(255) NOT NULL,
    DIA_CHI VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    GIOI_TINH VARCHAR(255) NOT NULL
);
CREATE TABLE NGAY (
    NGAY DATE PRIMARY KEY
);
CREATE TABLE CHI_TIET_PHIEU_NHAP (
    #KHO_MA_PHIEU_NHAP INT FOREIGN KEY REFERENCES KHO_HANG(MA_PHIEU_NHAP),
    #MA_DONG_SAN_PHAM INT FOREIGN KEY REFERENCES DONG_SAN_PHAM(MA_DONG_SAN_PHAM),
    #MA_PHIEU_NHAP INT FOREIGN KEY REFERENCES PHIEU_NHAP(MA_PHIEU_NHAP),
    soLuongNhap INT NOT NULL,
    gianhap DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (#KHO_MA_PHIEU_NHAP, #MA_DONG_SAN_PHAM, #MA_PHIEU_NHAP)
);
CREATE TABLE Nha_cung_cap (
    MA_NCC INT PRIMARY KEY,
    TEN_NCC VARCHAR(255) NOT NULL,
    DIA_CHI VARCHAR(255) NOT NULL,
    SDT VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);
